version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  node-install-packages:
    working_directory: /app
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages

workflows:
  wf-pipeline:
    jobs:
      - node-install-packages
      - node/run:
          app-dir: /app
      - node/test:
          app-dir: /app
          run-command: test
          test-results-for: jest