version: 2.1
jobs:
  test_build_app:
    working_directory: ~/app
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: |
            npm install --save

workflows:
  test_build_app:
    jobs:
      - run_tests  