version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10  

jobs:
  job-test-installDependencies:
    working_directory: ~/app
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: |
            npm install --save

heroku/deploy-via-git:
      working_directory: ~/app

workflows:
  wf-test:
    jobs:
      - job-test-installDependencies

  wf-deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only: main