version: 2.1

orbs:
  node: circleci/node@4.7
  terraform: circleci/terraform@3.0.1

executors:
  docker-executor:
    environment:
      IMAGE_NAME: thdesous/cicd-webapp-nodejs
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASS

jobs:
  checkout-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          app-dir:  ~/project/app
          pkg-manager: npm
      - run:         
          name: Run tests
          command: |
            cd app/
            npm test
          when: always
      - store_test_results:
          path: ~/project/app/test
      - store_artifacts:
          path: ~/project/app/test
  
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:         
          name: Build Docker image
          command: |
            cd app/
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar            

  publish-image:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest


  deploy:
    executor: terraform/default 
    working_directory: ~/project
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    executor: terraform/default
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - terraform/init:
          path: .
      - terraform/plan:
          path: .
      - terraform/destroy:
          path: .

workflows:
  ci-cd:
    jobs:
    # - checkout-test
    # - build:
    #     requires:
    #       - checkout-test
    # - publish-image:
    #     requires:
    #       - build
    - deploy
    - continue-destroy:
        requires:
          - deploy
        type: approval
    - destroy:
        requires:
          - continue-destroy    