version: 2.1
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      # - run:
      #     name: Run App
      #     command: npm start
      - run:
          name: Run Tests
          command: cd npm test

workflows:
  my-workflow:
    jobs:
      - test