version: 2.1
jobs:
  job_build_app:
    working_directory: ~/app
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: |
            npm install --save

workflows:
  workflow_builds:
    jobs:
      - job_build_app