version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm cache clean --force
            npm install --save
      # - run:
      #     name: Run Unit Tests
      #     command: |
      #       ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results


workflows:
  my-workflow:
    jobs:
      - install-dependencies
      - node/test:
          test-results-for: mocha 
          test-results-path: ~/project/app/test/test-results 
          app-dir: ~/project/app