version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  install-dependencies:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          app-dir:  ~/project/app
          pkg-manager: npm
      - run:         
          name: Run tests
          command: |
            cd app/
            npm test --reporter mocha-junit-reporter --reporter-options mochaFile=./test_results.xml
      - store_test_results:
          path: ~/project/app/test
      - store_artifacts:
          path: ~/project/app/test

workflows:
  my-workflow:
    jobs:
      - install-dependencies