version: 2.1
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:12
    working_directory: ~/project/app
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm test
      - store_test_results:
          path: ~/project/app/test/test-results 


workflows:
  my-workflow:
    jobs:
      - install-dependencies