version: 2.1
working_directory: ~/app
jobs:
  
  install-packages:
    working_directory: ~/app
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install

  run-app:
    working_directory: ~/app
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:      
          name: Run App
          command: npm start

  run-tests:
    working_directory: ~/app
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Run Tests
          command: npm test

workflows:
  my-workflow:
    jobs:
      - install-packages
      - run-app:
          requires:
            - install-packages
      - run-tests:
          requires:
            - run-app
