version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run App
          command: |
            ls -al
            pwd

      - run:
          name: Run Tests
          command: npm test

workflows:
  my-workflow:
    jobs:
      - test