orbs:
  docker: circleci/docker@1.5.0
version: 2.1

executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: $DOCKERHUB_USERNAME/cicd-webapp-nodejs:latest
    docker:
      - image: circleci/node:latest
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_ACCESS_TOKEN

jobs:
    publishLatestToHub: 
      executor: docker-publisher
      steps: 
        - checkout
        - setup_remote_docker
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
              docker build -t $IMAGE_NAME .
              docker push $IMAGE_NAME

workflows:
  version: 2
  build-master:
    jobs:
      - publishLatestToHub
