version: 2.1
jobs:
  run_app:
    docker:
      - image: thdesous/cicd-webapp-nodejs:latest
    steps:
      - checkout
      # - run: 
      #     name: Install npm dependencies
      #     command: |
      #       npm install --save
      # - run: 
      #     name: Start service
      #     command: |
      #       npm start
      - run: 
          name: Docker run
          command: |
            docker run thdesous/cicd-webapp-nodejs:latest
workflows:
  build:
    jobs:
      - run_app
  